export const PERMISSIONS = [
  'super_admin.all',
  'school.manage',
  'users.manage',
  'roles.assign',
  'class.manage',
  'class.view',
  'class.supervise',
  'attendance.record',
  'attendance.verify',
  'attendance.view_all',
  'attendance.amend',
  'restriction.view',
  'program.view',
  'program.view_others',
  'program.edit',
  'program.edit_template',
  'ethics.write',
  'ethics.review',
  'routing.handle',
  'routing.start',
  'analytics.view',
  'dashboard.admin',
  'reslife.manage',
  'dorm.captain',
  'dorm.roll_call',
  'dorm.view_all',
  'dorm.view_own',
  'success_story.verify',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
